Repository K-Fet/K-App, pull requests merged in 2018-06, with the labels that each got.

#258 Add migration system (up to date with models change since last version)
  package.json
  tools/migrations/00-Update-tasks.js
  tools/migrations/migrate.js
  tools/update.sh
  yarn.lock
Labels: BACK

#262 Update favicon
  client/src/assets/android-chrome-192x192.png
  client/src/assets/android-chrome-512x512.png
  client/src/assets/apple-touch-icon.png
  client/src/assets/browserconfig.xml
  client/src/assets/favicon-16x16.png
  client/src/assets/favicon-32x32.png
  client/src/assets/favicon.ico
  client/src/assets/mstile-144x144.png
  client/src/assets/mstile-150x150.png
  client/src/assets/mstile-310x150.png
  client/src/assets/mstile-310x310.png
  client/src/assets/mstile-70x70.png
  client/src/assets/safari-pinned-tab.svg
  client/src/assets/site.webmanifest
  client/src/index.html
Labels: FRONT

#264 Order res in services
  server/app/services/barman-service.js
  server/app/services/kommission-service.js
  server/app/services/member-service.js
  server/app/services/role-service.js
  server/app/services/template-service.js
Labels: BACK

#265 Set current day to today in planning
  client/src/app/services/planning/planning.component.ts
Labels: FRONT

#255 Barman service number
  client/src/app/_models/Barman.ts
  client/src/app/app.module.ts
  client/src/app/services/barman-service-number/barman-service-number.component.html
  client/src/app/services/barman-service-number/barman-service-number.component.ts
  client/src/app/services/services-explorer/services-explorer.component.html
  client/src/app/services/services-explorer/services-explorer.component.ts
Labels: FRONT

#268 Implement swipe
  client/package.json
  client/src/app/menu/menu.component.ts
  client/yarn.lock
Labels: FRONT

#269 Footer implementation
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/footer/footer.component.html
  client/src/app/footer/footer.component.scss
  client/src/app/footer/footer.component.ts
  client/src/app/menu/menu.component.scss
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
Labels: FRONT

#270 Design changes
  client/angular.json
  client/src/app/barmen/list/barmen-list.component.html
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/footer/footer.component.html
  client/src/app/footer/footer.component.scss
  client/src/app/kommissions/list/kommissions-list.component.html
  client/src/app/members/list/members-list.component.html
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
  client/src/app/roles/list/roles-list.component.html
  client/src/app/services/list/services-list.component.html
  client/src/app/special-accounts/list/special-accounts-list.component.html
  client/src/app/templates/list/templates-list.component.html
  client/src/app/templates/view/template-view.component.html
  client/src/index.html
  client/src/styles.scss
  client/src/theme.scss
Labels: FRONT

#273 Task UX implementation
  client/src/app/_models/Kommission.ts
  client/src/app/_models/Task.ts
  client/src/app/_models/index.ts
  client/src/app/_services/barman.service.ts
  client/src/app/_services/index.ts
  client/src/app/_services/task.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/footer/footer.component.scss
  client/src/app/home-page/home-page.component.html
  client/src/app/home-page/home-page.component.ts
  client/src/app/kommissions/list/kommissions-list.component.html
  client/src/app/kommissions/list/kommissions-list.component.scss
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/kommissions/view/kommission-view.component.html
  client/src/app/kommissions/view/kommission-view.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/services/barman-service-number/barman-service-number.component.ts
  client/src/app/tasks/edit-new/task-edit-new.component.html
  client/src/app/tasks/edit-new/task-edit-new.component.ts
  client/src/app/tasks/list/tasks-list.component.html
  client/src/app/tasks/list/tasks-list.component.scss
  client/src/app/tasks/list/tasks-list.component.ts
  client/src/app/tasks/my-tasks/my-tasks.component.html
  client/src/app/tasks/my-tasks/my-tasks.component.scss
  client/src/app/tasks/my-tasks/my-tasks.component.ts
  client/src/app/tasks/tasks.helpers.ts
  client/src/app/tasks/view/task-view.component.html
  client/src/app/tasks/view/task-view.component.scss
  client/src/app/tasks/view/task-view.component.ts
  client/src/theme.scss
  client/yarn.lock
  server/app/controllers/me-controller.js
  server/app/middlewares/is-barman.js
  server/app/routes/me.js
  server/app/services/task-service.js
  yarn.lock
Labels: FRONT

#275 Add code field to request body (PUT /me)
  client/src/app/_services/me.service.ts
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.ts
  client/src/app/special-accounts/new/special-account-new.component.html
Labels: FRONT

#208 Contact forms
  README.md
  client/package.json
  client/src/app/_helpers/errors.400.ts
  client/src/app/_services/contact.service.ts
  client/src/app/_services/index.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/contacts/concert/concert-contact.component.html
  client/src/app/contacts/concert/concert-contact.component.ts
  client/src/app/contacts/event/event-contact.component.html
  client/src/app/contacts/event/event-contact.component.ts
  client/src/app/contacts/lost/lost-contact.component.html
  client/src/app/contacts/lost/lost-contact.component.ts
  client/src/app/contacts/website/website-contact.component.html
  client/src/app/contacts/website/website-contact.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
  client/yarn.lock
  package.json
  server/app/controllers/contact-controller.js
  server/app/routes/contact.js
  server/app/routes/index.js
  server/app/services/auth-service.js
  server/app/services/mail-service.js
  server/app/services/recaptcha-service.js
  server/config/contactForm.js
  server/resources/contact-form-field-translations.js
  server/resources/email-templates.js
  server/resources/emails/reset-password.html
  server/resources/emails/username-confirm-change.html
  server/resources/emails/username-update-information.html
  server/resources/emails/verify-username.html
  server/resources/emails/welcome.html
  tools/dev-scripts/populate-db.js
  tools/init.js
  tools/migrations/00-Update-tasks.js
  tools/migrations/migrate.js
  tools/prod-scripts/account.js
  tools/prod-scripts/backup.js
  tools/prod-scripts/email.js
  tools/prod-scripts/jwt.js
  tools/prod-scripts/loader.js
  tools/prod-scripts/mysql.js
  tools/prod-scripts/proxy.js
  tools/prod-scripts/systemd.js
  tools/prod-scripts/util.js
  tools/release.js
  tools/update.sh
Labels: BACK, FRONT

#267 Fix #266
  client/src/app/_services/auth.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/auth/cancel-email-update/cancel-email-update.component.html
  client/src/app/auth/cancel-email-update/cancel-email-update.component.ts
  server/app/controllers/auth-controller.js
  server/app/routes/auth.js
  server/app/services/auth-service.js
  server/app/services/mail-service.js
  server/resources/email-templates.js
Labels: BACK, FRONT

#274 Home page improvement
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/feed/feed.component.html
  client/src/app/feed/feed.component.scss
  client/src/app/feed/feed.component.ts
  client/src/app/footer/footer.component.scss
  client/src/app/home-page/home-page.component.html
  client/src/app/home-page/home-page.component.scss
  client/src/app/home-page/home-page.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
  client/src/app/presentation/presentation.component.html
  client/src/app/presentation/presentation.component.scss
  client/src/app/presentation/presentation.component.ts
  client/src/assets/img/presentation/baby.jpg
  client/src/theme.scss
Labels: BACK, FRONT

#276 Feed/FeedObject models & endpoints
  server/app/controllers/category-controller.js
  server/app/controllers/feed-object-controller.js
  server/app/models/category.js
  server/app/models/feed-object.js
  server/app/models/index.js
  server/app/models/media.js
  server/app/models/schemas.js
  server/app/routes/category.js
  server/app/routes/feed-object.js
  server/app/routes/feed.js
  server/app/routes/index.js
  server/app/routes/special-accounts.js
  server/app/services/category-service.js
  server/app/services/feed-object-service.js
  server/config/permissions.js
Labels: BACK

#278 Implement password update email notification
  server/app/controllers/contact-controller.js
  server/app/services/auth-service.js
  server/app/services/mail-service.js
  server/resources/email-templates.js
Labels: BACK
