Repository K-Fet/K-App, pull requests merged in 2018-05, with the labels that each got.

#196 Fix services bugs
  client/src/app/services/open-services/open-services.component.html
  client/src/app/services/open-services/open-services.component.ts
  server/app/services/service-service.js
Labels: FRONT, bug

#194 Change dashboard-barman to dynamic services-explorer
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/dashboard-barman/dashboard-barman.component.ts
  client/src/app/menu/menu.component.ts
  client/src/app/services/services-explorer/services-explorer.component.html
  client/src/app/services/services-explorer/services-explorer.component.ts
Labels: FRONT, enhancement

#201 Fix padding issue if width > 600px
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
Labels: FRONT, bug

#198 Service CRUD components + Change datetime module
  client/package.json
  client/src/app/_helpers/material.module.ts
  client/src/app/_helpers/roles.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/menu/menu.component.ts
  client/src/app/services/edit/service-edit.component.html
  client/src/app/services/edit/service-edit.component.ts
  client/src/app/services/list/services-list.component.html
  client/src/app/services/list/services-list.component.ts
  client/src/app/services/new/service-new.component.html
  client/src/app/services/new/service-new.component.ts
  client/src/app/services/open-services/open-services.component.html
  client/src/styles.scss
  client/yarn.lock
Labels: FRONT, enhancement

#223 Fix #222
  client/src/app/_services/barman.service.ts
Labels: FRONT, bug

#218 Fix #207
  server/app/services/auth-service.js
Labels: BACK, bug

#219 Fix #215 & #216
  client/src/app/barmen/list/barmen-list.component.html
  client/src/app/barmen/list/barmen-list.component.ts
  client/src/app/kommissions/list/kommissions-list.component.html
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/roles/list/roles-list.component.html
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/templates/list/templates-list.component.html
Labels: FRONT, bug

#220 Fix #210
  client/src/app/barmen/view/barman-view.component.html
Labels: FRONT, bug

#209 Allowing different HOST headers to be used in ng serve
  client/package.json
Labels: FRONT, discussion

#221 Implement loader for every HTTP request
  client/src/app/_helpers/request.interceptor.ts
  client/src/app/_models/loader.ts
  client/src/app/_services/index.ts
  client/src/app/_services/loader.service.ts
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/loader/loader.component.css
  client/src/app/loader/loader.component.html
  client/src/app/loader/loader.component.ts
Labels: FRONT, enhancement

#227 Fix #226
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
Labels: FRONT, bug

#217 Update angular to version 6
  README.md
  client/.angular-cli.json
  client/angular.json
  client/package.json
  client/src/app/_guards/edit.guard.ts
  client/src/app/_helpers/request.interceptor.ts
  client/src/app/_services/auth.service.ts
  client/src/app/_services/barman.service.ts
  client/src/app/_services/kommission.service.ts
  client/src/app/_services/loader.service.ts
  client/src/app/_services/me.service.ts
  client/src/app/_services/member.service.ts
  client/src/app/_services/permission.service.ts
  client/src/app/_services/role.service.ts
  client/src/app/_services/service.service.ts
  client/src/app/_services/special-account.service.ts
  client/src/app/barmen/list/barmen-list.component.ts
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/loader/loader.component.ts
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/services/list/services-list.component.ts
  client/src/app/services/plan-my-services/plan-my-services.component.html
  client/src/app/services/planning/planning.component.html
  client/src/app/special-accounts/list/special-accounts-list.component.ts
  client/src/app/templates/list/templates-list.component.ts
  client/yarn.lock
Labels: FRONT, enhancement

#225 Fix #224
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/edit/barman-edit.component.ts
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/new/barman-new.component.ts
  client/yarn.lock
  server/app/models/barman.js
Labels: FRONT, bug

#231 Fix #229
  client/src/app/_guards/active.guard.ts
  client/src/app/_guards/edit.guard.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/services/my-services/my-services.component.ts
  client/src/app/services/services-explorer/services-explorer.component.html
  client/src/app/services/services-explorer/services-explorer.component.ts
  server/app/controllers/me-controller.js
  server/app/services/barman-service.js
Labels: BACK, FRONT

#235 Hot fix for v.1.1.0
  client/src/app/_helpers/roles.ts
  client/src/app/_services/auth.service.ts
  client/src/app/app.routing.ts
  server/app/services/auth-service.js
  server/resources/emails/welcome.html
Labels: BACK, FRONT, bug

#240 Fix #239
  client/src/app/_helpers/errors.400.ts
  client/src/app/_models/Service.ts
  client/src/app/services/plan-my-services/plan-my-services.component.html
  server/app/services/barman-service.js
Labels: BACK, FRONT

#241 Change `username` to `email` only in view
  client/src/app/auth/login/login.component.html
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/dialogs/reset-password/reset-password.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/list/special-accounts-list.component.html
  client/src/app/special-accounts/new/special-account-new.component.html
Labels: FRONT

#192 Templates management
  client/src/app/_models/Template.ts
  client/src/app/_services/template.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/templates/edit/template-edit.component.html
  client/src/app/templates/edit/template-edit.component.ts
  client/src/app/templates/list/templates-list.component.html
  client/src/app/templates/list/templates-list.component.ts
  client/src/app/templates/new/templates-new.component.html
  client/src/app/templates/new/templates-new.component.ts
  client/src/app/templates/view/template-view.component.html
  client/src/app/templates/view/template-view.component.ts
  server/app/models/template.js
Labels: FRONT

#243 Update task BACK (implement marco comments)
  server/app/controllers/task-controller.js
  server/app/models/task.js
  server/app/services/task-service.js
Labels: BACK, Refactor

#247 Fix #245 & #211 & 206
  client/src/app/barmen/new/barman-new.component.ts
  client/src/app/services/plan-my-services/plan-my-services.component.html
  client/src/app/services/plan-my-services/plan-my-services.component.ts
  client/src/app/services/planning/planning.component.html
  client/src/app/services/planning/planning.component.ts
  server/app/controllers/barman-controller.js
  server/app/models/barman.js
Labels: FRONT, enhancement

#249 Fix #248
  client/src/app/services/plan-my-services/plan-my-services.component.html
  client/src/app/services/planning/planning.component.html
  client/src/styles.scss
Labels: FRONT, bug
