Repository K-Fet/K-App, pull requests merged in 2018-08, with the labels that each got.

#291 Change `username` to email
  client/src/app/_helpers/errors.400.ts
  client/src/app/_models/Barman.ts
  client/src/app/_models/ConnectedUser.ts
  client/src/app/_models/ConnectionInformation.ts
  client/src/app/_models/Day.ts
  client/src/app/_models/Role.ts
  client/src/app/_models/Service.ts
  client/src/app/_models/SpecialAccount.ts
  client/src/app/_models/Task.ts
  client/src/app/_services/auth.service.ts
  client/src/app/_services/template.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/auth/cancel-email-update/cancel-email-update.component.ts
  client/src/app/auth/define-password/define-password.component.html
  client/src/app/auth/define-password/define-password.component.ts
  client/src/app/auth/email-verification/email-verification.component.html
  client/src/app/auth/email-verification/email-verification.component.ts
  client/src/app/auth/login/login.component.html
  client/src/app/auth/login/login.component.ts
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/edit/barman-edit.component.ts
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/new/barman-new.component.ts
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/dialogs/reset-password/reset-password.component.html
  client/src/app/dialogs/reset-password/reset-password.component.ts
  client/src/app/home-page/home-page.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.ts
  client/src/app/special-accounts/list/special-accounts-list.component.html
  client/src/app/special-accounts/list/special-accounts-list.component.ts
  client/src/app/special-accounts/new/special-account-new.component.html
  client/src/app/special-accounts/new/special-account-new.component.ts
  client/src/app/tasks/list/tasks-list.component.ts
  server/app/controllers/auth-controller.js
  server/app/controllers/barman-controller.js
  server/app/controllers/me-controller.js
  server/app/controllers/special-account-controller.js
  server/app/models/connection-information.js
  server/app/routes/__tests__/auth.unit.test.js
  server/app/routes/auth.js
  server/app/services/auth-service.js
  server/app/services/barman-service.js
  server/app/services/mail-service.js
  server/app/services/special-account-service.js
  server/resources/email-templates.js
  tools/migrations/02-Remove-username-occurences.js
  tools/prod-scripts/account.js
Labels: Refactor, back, front

#294 Change description from string to text for kommission & role
  client/src/app/kommissions/edit/kommission-edit.component.html
  client/src/app/kommissions/edit/kommission-edit.component.ts
  client/src/app/kommissions/list/kommissions-list.component.html
  client/src/app/kommissions/list/kommissions-list.component.scss
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/kommissions/new/kommission-new.component.html
  client/src/app/kommissions/new/kommission-new.component.ts
  client/src/app/roles/edit/role-edit.component.html
  client/src/app/roles/edit/role-edit.component.ts
  client/src/app/roles/list/roles-list.component.html
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/roles/new/role-new.component.html
  client/src/app/roles/new/role-new.component.ts
  server/app/models/kommission.js
  server/app/models/role.js
  tools/migrations/03-Update-description.js
Labels: business, front

#296 Some fixs
  client/src/app/_helpers/error.handler.ts
  client/src/app/_services/auth.service.ts
  client/src/app/contacts/concert/concert-contact.component.html
  client/src/app/contacts/event/event-contact.component.html
  client/src/app/contacts/lost/lost-contact.component.html
  client/src/app/contacts/website/website-contact.component.html
  client/src/app/feed/feed.component.html
  client/src/app/feed/feed.component.scss
  client/src/app/home-page/home-page.component.html
  client/src/app/loader/loader.component.html
  client/src/app/loader/loader.component.scss
  client/src/app/loader/loader.component.ts
  client/src/app/menu/menu.component.ts
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/services/my-services/my-services.component.ts
  client/src/app/services/open-services/open-services.component.ts
  client/src/app/templates/new/templates-new.component.ts
  server/app/middlewares/is-barman.js
  server/app/models/template.js
Labels: back, bug, front

#299 Add rate limiting to auth operations
  client/src/app/_helpers/error.handler.ts
  package.json
  server/app/middlewares/auth-guard.js
  server/app/routes/auth.js
  server/app/routes/category.js
  server/app/routes/feed-object.js
  server/app/routes/index.js
  tools/prod-scripts/proxy.js
  yarn.lock
Labels: security
