Repository K-Fet/K-App, pull requests merged in 2018-02, with the labels that each got.

#77 Change model + barman update with associations, functionnal
  client/src/app/_models/AssociationChanges.ts
  client/src/app/_models/Barman.ts
  client/src/app/_models/Category.ts
  client/src/app/_models/ConnectionInformation.ts
  client/src/app/_models/Kommission.ts
  client/src/app/_models/Member.ts
  client/src/app/_models/Role.ts
  client/src/app/_models/Service.ts
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/edit/barman-edit.component.ts
  server/app/services/barman-service.js
Labels: BACK, FRONT

#79 Barman View with associations
  client/src/app/_services/barman.service.ts
  client/src/app/barmen/view/barman-view.component.html
Labels: FRONT

#82 Use Joi as validator
  package.json
  server/app/controllers/auth-controller.js
  server/app/controllers/barman-controller.js
  server/app/controllers/category-controller.js
  server/app/controllers/kommission-controller.js
  server/app/controllers/member-controller.js
  server/app/controllers/role-controller.js
  server/app/controllers/service-controller.js
  server/app/models/association-changes.js
  server/app/models/barman.js
  server/app/models/category.js
  server/app/models/connection-information.js
  server/app/models/kommission.js
  server/app/models/member.js
  server/app/models/role.js
  server/app/models/schemas.js
  server/app/models/service.js
  yarn.lock
Labels: BACK, enhancement

#65 Association requests on Barman-Service
  client/package-lock.json
  server/app/controllers/barman-controller.js
  server/app/models/barman.js
  server/app/routes/barmen.js
  server/app/routes/index.js
  server/app/services/barman-service.js
Labels: BACK

#78 Barman new with associations
  client/src/app/_models/ConnectionInformation.ts
  client/src/app/_services/category.service.ts
  client/src/app/_services/kommission.service.ts
  client/src/app/_services/member.service.ts
  client/src/app/_services/role.service.ts
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/new/barman-new.component.ts
  client/src/app/barmen/view/barman-view.component.html
Labels: FRONT

#88 Roles associations
  server/app/controllers/role-controller.js
  server/app/models/role.js
  server/app/services/role-service.js
Labels: BACK

#90 fixes in Role Associations
  server/app/services/role-service.js
Labels: BACK

#91 CategoriesAssociations + correction mineure syntaxe role
  server/app/controllers/category-controller.js
  server/app/controllers/role-controller.js
  server/app/services/category-service.js
  server/app/services/role-service.js
Labels: BACK

#93 Fix #81 God Father issue & Add plural for barman in sequelize
  server/app/models/barman.js
Labels: BACK

#85 Connected user information Full Stack
  client/src/app/_models/ConnectedUser.ts
  client/src/app/_models/SpecialAccount.ts
  client/src/app/_models/index.ts
  client/src/app/_services/login.service.ts
  client/src/app/app.module.ts
  client/src/app/connected-user-dialog/connected-user-dialog.component.html
  client/src/app/connected-user-dialog/connected-user-dialog.component.ts
  client/src/app/login/login.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.ts
  server/app/controllers/auth-controller.js
  server/app/routes/auth.js
  server/app/services/auth-service.js
Labels: BACK, FRONT
