Repository K-Fet/K-App, pull requests merged in 2018-03, with the labels that each got.

#94 Generate services with template system
  .eslintrc.json
  client/src/app/_models/Category.ts
  client/src/app/_models/Service.ts
  client/src/app/_models/index.ts
  client/src/app/_services/category.service.ts
  client/src/app/_services/index.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/categories/edit/category-edit.component.html
  client/src/app/categories/edit/category-edit.component.ts
  client/src/app/categories/list/categories-list.component.html
  client/src/app/categories/list/categories-list.component.scss
  client/src/app/categories/list/categories-list.component.ts
  client/src/app/categories/new/category-new.component.html
  client/src/app/categories/new/category-new.component.ts
  client/src/app/menu/menu.component.html
  server/app/controllers/category-controller.js
  server/app/controllers/service-controller.js
  server/app/models/category.js
  server/app/models/index.js
  server/app/models/schemas.js
  server/app/models/service.js
  server/app/models/services-template.js
  server/app/routes/categories.js
  server/app/routes/index.js
  server/app/routes/services.js
  server/app/services/auth-service.js
  server/app/services/barman-service.js
  server/app/services/category-service.js
  server/app/services/kommission-service.js
  server/app/services/member-service.js
  server/app/services/role-service.js
  server/app/services/service-service.js
  server/app/services/user-service.js
  server/index.js
  server/test/controllers/member-controller.js
  server/test/services/member-service.js
  server/utils/async-middleware.js
  server/utils/index.js
  server/utils/password-manager.js
  server/utils/query-checker.js
  server/utils/template-service.js
  tools/dev-scripts/populate-db.js
Labels: BACK

#97 delete connection information when deleting a barman
  server/app/models/barman.js
  server/app/services/barman-service.js
Labels: BACK

#118 Remove file
  client/package-lock.json
Labels: BACK, enhancement

#102 Services components
  client/package.json
  client/src/app/_models/ConnectedUser.ts
  client/src/app/_models/Day.ts
  client/src/app/_models/Service.ts
  client/src/app/_models/Template.ts
  client/src/app/_models/index.ts
  client/src/app/_services/barman.service.ts
  client/src/app/_services/index.ts
  client/src/app/_services/kommission.service.ts
  client/src/app/_services/login.service.ts
  client/src/app/_services/member.service.ts
  client/src/app/_services/role.service.ts
  client/src/app/_services/service.service.ts
  client/src/app/_services/template.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/barmen/edit/barman-edit.component.ts
  client/src/app/barmen/new/barman-new.component.ts
  client/src/app/connected-user-dialog/connected-user-dialog.component.html
  client/src/app/connected-user-dialog/connected-user-dialog.component.ts
  client/src/app/dashboard/dashboard.component.html
  client/src/app/login/login.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.ts
  client/src/app/services/my-services/my-services.component.html
  client/src/app/services/my-services/my-services.component.ts
  client/src/app/services/open-services/open-services.component.html
  client/src/app/services/open-services/open-services.component.ts
  client/src/app/services/plan-my-services/plan-my-services.component.html
  client/src/app/services/plan-my-services/plan-my-services.component.ts
  client/src/app/services/planning/planning.component.html
  client/src/app/services/planning/planning.component.ts
  client/src/app/services/week-picker/week-picker.component.html
  client/src/app/services/week-picker/week-picker.component.ts
  client/yarn.lock
  server/app/controllers/barman-controller.js
  server/app/controllers/member-controller.js
  server/app/controllers/service-controller.js
  server/app/services/auth-service.js
  server/app/services/barman-service.js
  server/app/services/service-service.js
  server/utils/template-service.js
Labels: BACK, FRONT

#92 Special account stack
  server/app/controllers/barman-controller.js
  server/app/controllers/special-account-controller.js
  server/app/models/schemas.js
  server/app/models/special-account.js
  server/app/routes/index.js
  server/app/routes/special-account.js
  server/app/services/barman-service.js
  server/app/services/kommission-service.js
  server/app/services/role-service.js
  server/app/services/special-account-service.js
  server/utils/helpers.js
  server/utils/index.js
Labels: BACK

#127 Refractor login component + implement ENTER key down
  client/src/app/login/login.component.html
  client/src/app/login/login.component.ts
Labels: FRONT, enhancement

#128 Implement confirmation dialog + Refractor
  client/src/app/app.module.ts
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/barmen/view/barman-view.component.ts
  client/src/app/confirmation-dialog/confirmation-dialog.component.html
  client/src/app/confirmation-dialog/confirmation-dialog.component.ts
  client/src/app/kommissions/list/kommissions-list.component.html
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/roles/list/roles-list.component.html
  client/src/app/roles/list/roles-list.component.ts
Labels: FRONT, enhancement

#130 Implement (ngSubmit) and remove key down
  client/src/app/login/login.component.html
  client/src/app/login/login.component.ts
Labels: FRONT, enhancement

#129 Fix logout error + implement Guest account type
  client/src/app/_models/ConnectedUser.ts
  client/src/app/_services/login.service.ts
  client/src/app/app.module.ts
  client/src/app/connected-user-dialog/connected-user-dialog.component.html
  client/src/app/connected-user-dialog/connected-user-dialog.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.ts
  client/src/app/services/my-services/my-services.component.ts
  client/src/app/services/plan-my-services/plan-my-services.component.ts
Labels: FRONT, bug

#125 Special account components
  client/src/app/_models/Permission.ts
  client/src/app/_models/SpecialAccount.ts
  client/src/app/_models/index.ts
  client/src/app/_services/index.ts
  client/src/app/_services/permission.service.ts
  client/src/app/_services/special-account.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/code-dialog/code-dialog.component.html
  client/src/app/members/list/members-list.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.ts
  client/src/app/special-accounts/list/special-accounts-list.component.html
  client/src/app/special-accounts/list/special-accounts-list.component.scss
  client/src/app/special-accounts/list/special-accounts-list.component.ts
  client/src/app/special-accounts/new/special-account-new.component.html
  client/src/app/special-accounts/new/special-account-new.component.ts
  server/app/controllers/special-account-controller.js
  server/app/models/schemas.js
  server/app/models/special-account.js
  server/app/routes/special-account.js
  server/app/services/special-account-service.js
Labels: BACK, FRONT, enhancement

#136 WAIT FOR #125: Navigation enhancement + loop for generating menu
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/kommissions/edit/kommission-edit.component.html
  client/src/app/kommissions/new/kommission-new.component.html
  client/src/app/members/edit/member-edit.component.html
  client/src/app/members/new/member-new.component.html
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.ts
  client/src/app/roles/edit/role-edit.component.html
  client/src/app/roles/new/role-new.component.html
Labels: FRONT, enhancement

#64 Update favicon
  client/src/android-chrome-192x192.png
  client/src/android-chrome-384x384.png
  client/src/apple-touch-icon.png
  client/src/browserconfig.xml
  client/src/favicon-16x16.png
  client/src/favicon-32x32.png
  client/src/favicon.ico
  client/src/index.html
  client/src/mstile-150x150.png
  client/src/safari-pinned-tab.svg
  client/src/site.webmanifest
Labels: FRONT, enhancement

#83 Jest migration
  .eslintrc.json
  .travis.yml
  README.md
  package.json
  server/app/services/auth-service.js
  server/app/services/member-service.js
  server/config/db.js
  server/config/sequelize.js
  server/db.js
  server/permissions-init.js
  server/test/.eslintrc.json
  server/test/controllers/member-controller.js
  server/test/mocha.env.js
  server/test/resources/fake-members-database.json
  server/test/services/member-service.js
  server/tests/int/members/delete-member.js
  server/tests/int/members/get-member-id.js
  server/tests/int/members/get-members.js
  server/tests/int/members/post-member.js
  server/tests/int/members/put-member.js
  server/tests/utils/setup-teardown-common.js
  yarn.lock
Labels: BACK, tests

#137 Change barman forms + improve connected user popup
  client/src/app/_guards/edit.guard.ts
  client/src/app/_guards/index.ts
  client/src/app/_models/ConnectedUser.ts
  client/src/app/_services/barman.service.ts
  client/src/app/_services/index.ts
  client/src/app/_services/me.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/edit/barman-edit.component.ts
  client/src/app/barmen/list/barmen-list.component.html
  client/src/app/barmen/list/barmen-list.component.ts
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/kommissions/list/kommissions-list.component.html
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/members/list/members-list.component.html
  client/src/app/members/list/members-list.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
  client/src/app/menu/menu.component.ts
  client/src/app/roles/list/roles-list.component.html
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.ts
  client/src/app/special-accounts/list/special-accounts-list.component.html
  client/src/app/special-accounts/list/special-accounts-list.component.ts
  client/src/app/special-accounts/new/special-account-new.component.html
  client/src/assets/android-chrome-192x192.png
  client/src/assets/android-chrome-384x384.png
  client/src/assets/apple-touch-icon.png
  client/src/assets/browserconfig.xml
  client/src/assets/favicon-16x16.png
  client/src/assets/favicon-32x32.png
  client/src/assets/mstile-150x150.png
  client/src/assets/safari-pinned-tab.svg
  client/src/assets/site.webmanifest
  server/app/controllers/me-controller.js
  server/app/services/barman-service.js
Labels: FRONT, enhancement

#140 fixes issues about the datepicker and the kommission display
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/edit/barman-edit.component.ts
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/new/barman-new.component.ts
  client/src/app/barmen/view/barman-view.component.html
Labels: FRONT

#152 Error handling
  client/src/app/_guards/auth.guard.ts
  client/src/app/_guards/index.ts
  client/src/app/_helpers/error.handler.ts
  client/src/app/_helpers/errors.400.ts
  client/src/app/_helpers/jwt.interceptor.ts
  client/src/app/_services/barman.service.ts
  client/src/app/_services/kommission.service.ts
  client/src/app/_services/login.service.ts
  client/src/app/_services/me.service.ts
  client/src/app/_services/member.service.ts
  client/src/app/_services/permission.service.ts
  client/src/app/_services/role.service.ts
  client/src/app/_services/service.service.ts
  client/src/app/_services/special-account.service.ts
  client/src/app/_services/template.service.ts
  client/src/app/_services/toaster.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/barmen/edit/barman-edit.component.ts
  client/src/app/barmen/new/barman-new.component.ts
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/barmen/view/barman-view.component.ts
  client/src/app/kommissions/edit/kommission-edit.component.ts
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/kommissions/new/kommission-new.component.ts
  client/src/app/login/login.component.ts
  client/src/app/members/edit/member-edit.component.ts
  client/src/app/members/list/members-list.component.ts
  client/src/app/members/new/member-new.component.ts
  client/src/app/menu/menu.component.ts
  client/src/app/roles/edit/role-edit.component.ts
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/roles/new/role-new.component.ts
  client/src/app/services/my-services/my-services.component.ts
  client/src/app/services/open-services/open-services.component.ts
  client/src/app/services/plan-my-services/plan-my-services.component.ts
  client/src/app/services/planning/planning.component.ts
  client/src/app/special-accounts/edit/special-account-edit.component.ts
  client/src/app/special-accounts/list/special-accounts-list.component.ts
  client/src/app/special-accounts/new/special-account-new.component.ts
Labels: FRONT, enhancement

#153 adding instance.reload() in services
  server/app/services/barman-service.js
  server/app/services/kommission-service.js
  server/app/services/role-service.js
  server/app/services/special-account-service.js
Labels: BACK, bug

#151 Service already choosen
  client/src/app/services/plan-my-services/plan-my-services.component.html
  client/src/app/services/plan-my-services/plan-my-services.component.ts
Labels: FRONT, bug

#154 Add statuts validation + implement code pattern validator
  client/src/app/_validators/checkbox.validator.ts
  client/src/app/code-dialog/code-dialog.component.html
  client/src/app/code-dialog/code-dialog.component.ts
  client/src/app/members/edit/member-edit.component.html
  client/src/app/members/edit/member-edit.component.ts
  client/src/app/members/new/member-new.component.html
  client/src/app/members/new/member-new.component.ts
  client/src/assets/Statuts ARGIL.pdf
Labels: FRONT, bug
