Repository K-Fet/K-App, pull requests merged in 2018-04, with the labels that each got.

#156 Templates routes
  server/app/controllers/service-controller.js
  server/app/controllers/template-controller.js
  server/app/models/index.js
  server/app/models/schemas.js
  server/app/models/template.js
  server/app/routes/index.js
  server/app/routes/services.js
  server/app/routes/templates.js
  server/app/services/service-service.js
  server/app/services/template-service.js
Labels: BACK, enhancement

#143 Password components + refractoring
  client/src/app/_guards/edit.guard.ts
  client/src/app/_helpers/equal-validator.directive.ts
  client/src/app/_helpers/errors.400.ts
  client/src/app/_models/ConnectionInformation.ts
  client/src/app/_services/auth.service.ts
  client/src/app/_services/index.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/auth/define-password/define-password.component.html
  client/src/app/auth/define-password/define-password.component.ts
  client/src/app/auth/login/login.component.html
  client/src/app/auth/login/login.component.ts
  client/src/app/auth/username-verification/username-verification.component.html
  client/src/app/auth/username-verification/username-verification.component.ts
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/edit/barman-edit.component.ts
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/new/barman-new.component.ts
  client/src/app/barmen/view/barman-view.component.ts
  client/src/app/dialogs/code-dialog/code-dialog.component.html
  client/src/app/dialogs/code-dialog/code-dialog.component.ts
  client/src/app/dialogs/confirmation-dialog/confirmation-dialog.component.html
  client/src/app/dialogs/confirmation-dialog/confirmation-dialog.component.ts
  client/src/app/dialogs/reset-password/reset-password.component.html
  client/src/app/dialogs/reset-password/reset-password.component.ts
  client/src/app/kommissions/list/kommissions-list.component.ts
  client/src/app/login/login.component.ts
  client/src/app/members/list/members-list.component.ts
  client/src/app/menu/menu.component.ts
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/services/my-services/my-services.component.ts
  client/src/app/services/open-services/open-services.component.ts
  client/src/app/services/plan-my-services/plan-my-services.component.ts
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.ts
  client/src/app/special-accounts/list/special-accounts-list.component.ts
  client/src/app/special-accounts/new/special-account-new.component.ts
  package.json
  server/app/controllers/auth-controller.js
  server/app/controllers/special-account-controller.js
  server/app/services/auth-service.js
  server/app/services/mail-service.js
  server/app/services/special-account-service.js
  server/config/permissions.js
  yarn.lock
Labels: FRONT, security

#163 Multiple bugfix
  server/app/controllers/template-controller.js
  server/app/services/auth-service.js
  server/app/services/barman-service.js
  server/app/services/special-account-service.js
  server/app/services/template-service.js
  server/config/permissions.js
  server/config/sequelize.js
Labels: BACK, bug

#150 Implement permissions for barman account (through roles)
  server/app/services/auth-service.js
Labels: BACK, bug

#166 Fix issue with delete bodies
  client/src/app/_services/barman.service.ts
  client/src/app/_services/kommission.service.ts
  client/src/app/_services/me.service.ts
  client/src/app/_services/member.service.ts
  client/src/app/_services/permission.service.ts
  client/src/app/_services/role.service.ts
  client/src/app/_services/service.service.ts
  client/src/app/_services/special-account.service.ts
  server/app/routes/barmen.js
  server/app/routes/kommissions.js
  server/app/routes/me.js
  server/app/routes/members.js
  server/app/routes/roles.js
  server/app/routes/services.js
  server/app/routes/special-account.js
  server/app/routes/templates.js
Labels: bug

#167 Layout enhancement
  client/src/app/barmen/edit/barman-edit.component.html
  client/src/app/barmen/list/barmen-list.component.html
  client/src/app/barmen/new/barman-new.component.html
  client/src/app/barmen/view/barman-view.component.html
  client/src/app/dashboard/dashboard.component.html
  client/src/app/kommissions/edit/kommission-edit.component.html
  client/src/app/kommissions/list/kommissions-list.component.html
  client/src/app/kommissions/new/kommission-new.component.html
  client/src/app/members/edit/member-edit.component.html
  client/src/app/members/list/members-list.component.html
  client/src/app/members/list/members-list.component.ts
  client/src/app/members/new/member-new.component.html
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
  client/src/app/menu/menu.component.ts
  client/src/app/roles/edit/role-edit.component.html
  client/src/app/roles/list/roles-list.component.html
  client/src/app/roles/new/role-new.component.html
  client/src/app/services/open-services/open-services.component.html
  client/src/app/services/plan-my-services/plan-my-services.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/list/special-accounts-list.component.html
  client/src/app/special-accounts/new/special-account-new.component.html
  client/src/styles.scss
Labels: FRONT, enhancement

#171 Front role system
  client/src/app/_helpers/roles.ts
  client/src/app/_services/auth.service.ts
  client/src/app/app.routing.ts
  client/src/app/menu/menu.component.ts
Labels: FRONT, enhancement

#172 Refractor menu
  client/src/app/_services/auth.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/auth/login/login.component.ts
  client/src/app/dashboard-barman/dashboard-barman.component.html
  client/src/app/dashboard-barman/dashboard-barman.component.ts
  client/src/app/dashboard/dashboard.component.ts
  client/src/app/menu/menu.component.ts
Labels: FRONT, enhancement

#165 Templates READ ONLY front
  client/src/app/_services/template.service.ts
  client/src/app/app.module.ts
  client/src/app/app.routing.ts
  client/src/app/menu/menu.component.ts
  client/src/app/services/my-services/my-services.component.html
  client/src/app/services/open-services/open-services.component.html
  client/src/app/services/open-services/open-services.component.ts
  client/src/app/services/plan-my-services/plan-my-services.component.html
  client/src/app/services/week-picker/week-picker.component.html
  client/src/app/templates/list/templates-list.component.html
  client/src/app/templates/list/templates-list.component.scss
  client/src/app/templates/list/templates-list.component.ts
  client/src/app/templates/new/templates-new.component.html
  client/src/app/templates/new/templates-new.component.ts
  client/src/app/templates/view/template-view.component.html
  client/src/app/templates/view/template-view.component.ts
  client/src/styles.scss
Labels: FRONT

#187 Fix #186 : Transactions not closed
  server/app/services/auth-service.js
Labels: BACK, bug

#188 Tools fixes
  tools/init.js
  tools/prod-scripts/account.js
  tools/prod-scripts/backup.js
  tools/prod-scripts/email.js
  tools/prod-scripts/jwt.js
  tools/prod-scripts/loader.js
  tools/prod-scripts/mysql.js
  tools/prod-scripts/proxy.js
  tools/prod-scripts/systemd.js
  tools/prod-scripts/util.js
Labels: BACK

#190 Fix express proxies
  tools/prod-scripts/proxy.js
  tools/prod-scripts/systemd.js
Labels: BACK, bug

#191 Fix issue with permissions
  client/src/app/_models/Permission.ts
  client/src/app/_services/permission.service.ts
  client/src/app/roles/edit/role-edit.component.html
  client/src/app/roles/list/roles-list.component.ts
  client/src/app/roles/new/role-new.component.html
  client/src/app/special-accounts/edit/special-account-edit.component.html
  client/src/app/special-accounts/new/special-account-new.component.html
  client/src/app/special-accounts/new/special-account-new.component.ts
  server/app/controllers/role-controller.js
  server/app/controllers/special-account-controller.js
  server/app/models/special-account.js
  server/app/services/permission-service.js
  server/utils/errors.js
  server/utils/index.js
Labels: bug, security

#195 Implement code check
  server/app/controllers/me-controller.js
Labels: BACK, bug, security
